/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorHashTable;
import Controlador.ControladorHojaCalculo;
import Modelo.Libro;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;


/**
 *
 * @author Victor
 */
public class HojaCalculo extends javax.swing.JFrame {

    /**
     * Creates new form HojaCalculo
     */
    public HojaCalculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuArchivo = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuHojaNueva = new javax.swing.JMenuItem();
        jMenuTablaHash = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jMenu1.setText("Archivo");

        jMenuHojaNueva.setText("Nueva hoja");
        jMenuHojaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHojaNuevaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuHojaNueva);

        jMenuTablaHash.setText("Tabla Hash");
        jMenu1.add(jMenuTablaHash);

        jMenuArchivo.add(jMenu1);

        setJMenuBar(jMenuArchivo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public JMenuItem getMenuHojaNueva() {
        return jMenuHojaNueva;
    }
    public JMenuItem getMenuTablaHash() {
        return jMenuTablaHash;
    }

    public void agregarHoja(String titulo, JPanel panelHoja) {
        jTabbedPane1.addTab(titulo, panelHoja);
        int index = jTabbedPane1.indexOfTab(titulo);

        JPanel tabPanel = new JPanel(new BorderLayout());
        tabPanel.add(new JLabel(titulo), BorderLayout.CENTER);
        JButton closeButton = new JButton("X");
        closeButton.setPreferredSize(new Dimension(18, 18));
        closeButton.setMargin(new Insets(0, 0, 0, 0));
        closeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jTabbedPane1.remove(panelHoja);
            }
        });
        tabPanel.add(closeButton, BorderLayout.EAST);
        jTabbedPane1.setTabComponentAt(index, tabPanel);
    }
    private void jMenuHojaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHojaNuevaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuHojaNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HojaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HojaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HojaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HojaCalculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HojaCalculo vista = new HojaCalculo();
                Libro libro = new Libro();
                new ControladorHojaCalculo(vista, libro);
                vista.setVisible(true);
                new ControladorHashTable(vista);
                vista.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuArchivo;
    private javax.swing.JMenuItem jMenuHojaNueva;
    private javax.swing.JMenuItem jMenuTablaHash;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
